name: Maven Deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install GPG Secret Key
        run: cat <(echo -e "${{ secrets.OSSRH_GPG_SECRET_KEY }}") | gpg --batch --import
      - name: Set Up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Set Up Maven Settings
        uses: s4u/maven-settings-action@v2.8.0
        with:
          servers: |
            [{
              "id": "ossrh",
              "username": "${{ secrets.OSSRH_USERNAME }}",
              "password": "${{ secrets.OSSRH_TOKEN }}"
            },
            {
              "id": "gpg.passphrase",
              "passphrase": "${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}",
              "configuration": {}
            }]
      - name: Maven Verify
        run: mvn --batch-mode verify
      - name: Maven Deploy
        run: mvn --batch-mode -DskipTests=true deploy
