name: Maven Compile

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - name: Set Up JDK 17
        uses: actions/setup-java@v4.2.2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn --batch-mode clean compile
  trigger-deploy:
    runs-on: ubuntu-latest
    needs: compile
    outputs:
      CONTINUE_JOBS: ${{ steps.trigger-deploy-job.outputs.CONTINUE_JOBS }}
    steps:
      - name: trigger-deploy-job
        id: trigger-deploy-job
        uses: benhamiltonpro/manual-trigger@v1.0.2
        with:
          RUN_NAME: "deploy"
  deploy:
    runs-on: ubuntu-latest
    needs: trigger-deploy
    if: ${{ needs.trigger-deploy.outputs.CONTINUE_JOBS == 'true' }}
    steps:
      - uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0
      - name: Install GPG Secret Key
        run: cat <(echo -e "${{ secrets.OSSRH_GPG_SECRET_KEY }}") | gpg --batch --import
      - name: Set Up JDK 17
        uses: actions/setup-java@v4.2.2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Set Up Maven Settings
        uses: s4u/maven-settings-action@v3.0.0
        with:
          servers: |
            [{
              "id": "ossrh",
              "username": "${{ secrets.OSSRH_USERNAME }}",
              "password": "${{ secrets.OSSRH_TOKEN }}"
            },
            {
              "id": "gpg.passphrase",
              "passphrase": "${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}",
              "configuration": {}
            }]
      - name: Maven Verify
        run: mvn --batch-mode verify
      - name: Maven Deploy
        run: mvn --batch-mode -DskipTests=true deploy
